// Auto-init InariWatch error capture. Generated by the InariWatch
// GitHub App on first install — feel free to edit or remove. See
// https://inariwatch.com/docs/quickstart for details.
import "@inariwatch/capture/auto";
import { captureRequestError } from "@inariwatch/capture";
export const onRequestError = captureRequestError;
